### ISSUE TITLE
Deploy: 05 - Configurar o Banco de Dados na Nuvem

### ISSUE THREAD

**Issue by wagnermor** [PowerGreenBr/backEnd#19]
- [x] Na Source Folder src/main/resources, criar os arquivos application-dev.properties (Configuração do Banco de dados local) e application-prod.properties (Configuração do Banco de dados na nuvem), como mostra a imagem abaixo:

![Image](https://user-images.githubusercontent.com/47096330/218352968-399b231e-512f-452d-ab48-5a98f748fa2c.png)

```Pg. 24 da documentação```

**Comment by wagnermor** [comment]
- [ ] Na Source Folder src/main/resources, criar os arquivos application-dev.properties (Configuração do Banco de dados local) e application-prod.properties (Configuração do Banco de dados na nuvem), como mostra a imagem abaixo:


![Image](https://user-images.githubusercontent.com/47096330/218352968-399b231e-512f-452d-ab48-5a98f748fa2c.png)

**Comment by jess59cavalcante** [comment]
Deploy - Configuração Banco de Dados Na Nuvem
